Feat/timer #13
AndroidNetrunner/decrypto pull request #28
Opened 2022-02-16 15:26 UTC by 071yoon

## ✅ PR check list

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message가 적절한지 확인해주세요.
- [x] 적절한 branch로 요청했는지 확인해주세요.
- [x] Assignees, Label을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 📝 Changes

https://user-images.githubusercontent.com/66371206/154296387-280855c8-7d42-4f74-8107-9ce1ee08a6c5.mov

- Timer를 시각적으로 얼마나 남았는지 보여주는 컴포넌트입니다.
- gameTime 을 15, 30, 60 중 하나로 받아서 넘겨주면 각각 15초 30초 60초짜리 타이머로 보여줍니다
- 해당 영상은 30초짜리 타이머입니다

closes: #13

<br/>

## 👨🏻‍💻 Test Checklist

- [ ] 이러한 테스트를 했어요!

## 📌 변경 및 주의 사항

+ 추후에 18번 줄인 console.log 를 찍는 부분이 서버에 시간이 끝났고, 자동제출을 하고 라운드가 넘어가게 되는 부분을 추가해야됩니다

+ 제가 처음에 테스트를 하다가 material/ui 를 넣어보다가 package-lock.json 에 그러한 부분들이 추가가 됐습니다. 그런데 로딩바로 쓰이기 딱 좋아서 일단 남겨뒀습니다. [로딩바로 쓰이기 좋은 Progress Bar](https://mui.com/components/progress/)

<br/>

2022-02-16 16:09 UTC, AndroidNetrunner reviewed
오오...! 저 원 디자인은 구현이 어려울 것 같아서 제가 포기한 건데...! 저걸 하시다니!

혹시 저 원 위에 남은 시간을 숫자로 쓰는 건 가능할까요?

2022-02-16 16:13 UTC, 071yoon commented
> 



> 오오...! 저 원 디자인은 구현이 어려울 것 같아서 제가 포기한 건데...! 저걸 하시다니!
> 
> 혹시 저 원 위에 남은 시간을 숫자로 쓰는 건 가능할까요?

안그래도 제가 원 안에 남은 시간을 표현하려고 했는데, 디자인도 구리고 실력문제로 나아가지 못했슴미다... 추후에 제가 룰북 모달창 만들고 나서 다시 만져보겠습니다!!

2022-02-17 08:55 UTC, 071yoon commented
https://user-images.githubusercontent.com/66371206/154440192-cc67bb61-d2c8-4836-912d-91237cb939dc.mov

수정 완료했습니다.

2022-02-17 13:42 UTC, AndroidNetrunner requested changes
제가 원하던 그림이었습니다! 하지만 테스트를 위해...

2022-02-17 13:42 UTC, AndroidNetrunner approved these changes, later dismissed

2022-02-18 06:05 UTC, Seojunhwan reviewed
요거 하나만 확인해 주세요!

2022-02-18 06:05 UTC, Seojunhwan commented on src/Components/Timer.tsx
> +  .before {
`.before` 한 번 확인 부탁드립니당

2022-02-18 06:05 UTC, Seojunhwan commented on src/Components/Timer.tsx
> +  font-family: neodgm;
예비 폰트? 도 지정해주세요~!

2022-02-18 06:09 UTC, 071yoon commented on src/Components/Timer.tsx
> +  font-family: neodgm;
넹

2022-02-18 06:10 UTC, 071yoon commented on src/Components/Timer.tsx
> +  .before {
넵 확인했습니다

2022-02-18 06:21 UTC, Seojunhwan approved these changes
음 코드 맛있네요~

2022-02-21 05:29 UTC, AndroidNetrunner approved these changes
👍

2022-02-21 05:29 UTC, merged